CREATE TABLE [dbo].[PERSON] (
    [PERSON_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [FIRST_NAME]     VARCHAR (100) NOT NULL,
    [SURNAME]        VARCHAR (100) NOT NULL,
    [CELLPHONE]      VARCHAR (15)  NOT NULL,
    [EMAIL]          VARCHAR (250) NOT NULL,
    [ID_NUMBER]      VARCHAR (15)  NOT NULL,
    [PERSON_TYPE_ID] INT           NOT NULL,
    [MANAGER_ID]     INT           NULL,
    CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED ([PERSON_ID] ASC),
    CONSTRAINT [FK_Table_1_PERSON_TYPE] FOREIGN KEY ([PERSON_TYPE_ID]) REFERENCES [dbo].[PERSON_TYPE] ([PERSON_TYPE_ID])
);

