CREATE TABLE [dbo].[PERSON_TYPE] (
    [PERSON_TYPE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]    VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_PERSON_TYPE] PRIMARY KEY CLUSTERED ([PERSON_TYPE_ID] ASC)
);

