CREATE TABLE [dbo].[SALE] (
    [SALE_ID]  INT      IDENTITY (1, 1) NOT NULL,
    [CAR_ID]   INT      NOT NULL,
    [SALEDATE] DATETIME NULL,
    CONSTRAINT [PK_SALE] PRIMARY KEY CLUSTERED ([SALE_ID] ASC),
    CONSTRAINT [FK_SALE_SALE] FOREIGN KEY ([CAR_ID]) REFERENCES [dbo].[CAR] ([CAR_ID])
);

