CREATE PROCEDURE [dbo].[CAR_UPDATE]
(
	@CAR_ID INT,
	@MANUFACTURER_ID INT,
	@MODEL VARCHAR(100),
    @COLOUR VARCHAR(20),
    @ODOMETER_READING VARCHAR(25),
    @CONDITION_RATING VARCHAR(10),
    @PRICE INT,
    @MECHANIC_ID INT,
    @CLEANER_ID INT,
    @SALESPERSON_ID INT
)
AS
BEGIN
	UPDATE CAR SET
		 [MANUFACTURER_ID] = @MANUFACTURER_ID
		,[MODEL] = @MODEL
		,[COLOUR] = @COLOUR
		,[ODOMETER_READING] = @ODOMETER_READING
		,[CONDITION_RATING] = @CONDITION_RATING
		,[PRICE] = @PRICE
		,[MECHANIC_ID] = @MECHANIC_ID
		,[CLEANER_ID] = @CLEANER_ID
		,[SALESPERSON_ID] = @SALESPERSON_ID
	 
	WHERE
		CAR_ID = @CAR_ID
END
