CREATE PROCEDURE MANUFACTURER_UPDATE
(
	@MANUFACTURER_ID INT,
	@M_DESCRIPTION VARCHAR(100)
)
AS
BEGIN 
	UPDATE MANUFACTURER SET

		[M_DESCRIPTION] = @M_DESCRIPTION

	WHERE
		MANUFACTURER_ID = @MANUFACTURER_ID
END